export enum errorCodes {
    SUCCESSFUL,
    GENERIC_ERROR,
    ELEMENT_DOES_NOT_EXIST,
    NO_CONTENT,
    DUPLICATE_DATABASE_ENTRY,
    JOINING_ERROR,
    VALIDATION_ERROR,
    ATTRIBUTES_CLASHING,
    LACKING_QUERY_ELEMENTS,
    LACKING_PERFORMANCE_DATA
}