# workflow for å teste Oppgave 1 Build
name: Run Build and Run Tests on Oppgave_2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
       

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        

    - name: Install dependencies and test for oppgave_2
      continue-on-error: true
      run: |
        cd oppgave_2
        npm ci
        npm run build --if-present
        npm test
    
